plugins {
	id 'org.springframework.boot' version '2.2.4.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
	id 'idea'
	id 'application'
	id 'jacoco'
	id 'org.sonarqube' version '3.5.0.2730'
}

group = 'com.ev'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
	testImplementation('junit:junit:4.13')
}

test {
	useJUnitPlatform()
}

application {
	mainClassName = 'com.ev.EvApplication'
}
jacoco {
	toolVersion = "0.8.7"
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.enabled true
	}
}

sonarqube {
	properties {
		property "sonar.projectKey", "sonia125-s_spring-boot-rest-api_test"
		property "sonar.organization", "sonia125-s"
		property "sonar.host.url", System.getenv('SONAR_HOST_URL')
		property "sonar.login", System.getenv('SONAR_TOKEN')
		property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
	}
}